<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
delete from mh_menu;

insert into mh_menu values(1,'AZ버거 오리지널세트',8100,'/set_az.jpg',4,'최고 청정지역 호주 태즈매니아산 육즙 가득 순쇠고기 패티와  통밀발효종 효모가 사용되어 부드러운 브리오쉬 번 좋은 재료와 맛의 A to Z를 느낄 수 있는 프리미엄 제품');
insert into mh_menu values(2,'와규오리지널세트',9500,'/set_wagyu.jpg',4,'최고급 품질의 호주산 와규 100%를 사용해 부드러운 육질과 풍부한 육즙을 느낄 수 있는 프리미엄 버거');
insert into mh_menu values(3,'한우불고기콤보세트',7700,'/set_hanubul_combo.jpg',1,'100% 우리 한우로 만든 두툼한 패티와 부드럽고 촉촉한 포테이토번이 만나 더 맛있어진 프리미엄 버거 콤보 ');
insert into mh_menu values(4,'한우불고기세트',8400,'/set_hanubul.jpg',1,'100% 우리 한우로 만든 두툼한 패티와 부드럽고 촉촉한 포테이토번이 만나 더 맛있어진 프리미엄 버거 세트 ');
insert into mh_menu values(5,'모짜렐라인더버거세트',7500,'/set_moza.jpg',1,'자연산 모짜렐라 치즈에 노릇노릇한 베이컨, 레터스, 소스가 어우러진 풍부한 맛의 모짜렐라 인더버거 베이컨 ');
insert into mh_menu values(6,'모짜렐라더블팩세트',12500,'/set_moza_double.jpg',1,'대표 제품인 모짜렐라 인 더 버거 더블과 불고기버거를 동시에 즐길 수 있는 모짜렐라 더블팩');
insert into mh_menu values(7,'모짜렐라인더버거해쉬세트',7200,'/set_moza_hash.jpg',1,'자연산 모짜렐라 치즈가 풍성한 레터스와 소스를 만나 맛이 더욱 풍부해진 모짜렐라 인 더 버거 해쉬');
insert into mh_menu values(8,'원조빅불세트',7000,'/set_bigbul.jpg',1,'불고기 특유의 소스와 쇠고기의 진함을 배로 느끼는 제품 ');
insert into mh_menu values(9,'핫크리스피버거세트',6500,'/set_hotcri.jpg',1,'토마토와 레타스등의 야채와 하바네로香이 가미된 가슴살로 만든 매콤한 Premium 치킨버거 ');
insert into mh_menu values(10,'한우연인팩세트',13300,'/set_hanwu_yon.jpg',1,'한우불고기버거와 새우버거를 함께 즐길 수 있는 한우연인팩');
insert into mh_menu values(11,'한우명품세트',15100,'/set_hanwu_myong.jpg',1,'NEW한우불고기버거와 핫크리스피버거를 함께 즐길 수 있는 한우명품팩 ');
insert into mh_menu values(12,'새우버거세트',5600,'/set_sewu.jpg',1,'흰살생선과 새우맛이 살아있는 햄버거 세트 ');
insert into mh_menu values(13,'T-Rex버거세트',5600,'/set_trex.jpg',1,'번스보다 큰 통다리살 치킨패티를 활용한 버거제품 ');
insert into mh_menu values(14,'클래식치즈버거세트',6000,'/set_classic_cheese.jpg',1,'부드럽고 촉촉한 포테이토번과 풍부한 육즙의 두툼한 호주산 쇠고기패티로 본연의 맛을 꽉 채운 클래식 치즈버거 ');
insert into mh_menu values(15,'데리버거 세트',4700,'/set_deri.jpg',1,'풍성한 레터스에 마요네즈,독특한 데리소스가 포인트인 햄버거 세트 ');
insert into mh_menu values(16,'와규오리지널',7800,'/burger_wagyu.jpg',5,'최고급 품질의 호주산 와규 100%를 사용해 부드러운 육질과 풍부한 육즙을 느낄 수 있는 프리미엄 버거 ');
insert into mh_menu values(17,'모짜렐라인더버거베이컨',5800,'/burger_moza_bacon.jpg',2,'자연산 모짜렐라 치즈에 노릇노릇한 베이컨, 레터스, 소스가 어우러진 풍부한 맛의 모짜렐라 인더버거 베이컨 ');
insert into mh_menu values(18,'AZ버거오리지널',6400,'/burger_az.jpg',5,'최고 청정지역 호주 태즈매니아산 육즙 가득 순쇠고기 패티와  통밀발효종 효모가 사용되어 부드러운 브리오쉬 번  좋은 재료와 맛의 A to Z를 느낄 수 있는 프리미엄 제품 ');
insert into mh_menu values(19,'모짜렐라인더버거더블',5500,'/burger_moza.jpg',2,'자연산 모짜렐라 치즈에 고소한 해쉬브라운, 두툼한 미트패티를 더해 푸짐하게 즐기는 모짜렐라 인 더 버거 - 더블 ');
insert into mh_menu values(20,'모짜렐라인더버거해쉬',4700,'/burger_moza_hash.jpg',2,'자연산 모짜렐라 치즈가 풍성한 레터스와 소스를 만나 맛이 더욱 풍부해진 모짜렐라 인 더 버거 해쉬');
insert into mh_menu values(21,'원조빅불',5200,'/burger_bigbul.jpg',2,'불고기 특유의 소스와 쇠고기의 진함을 배로 느끼는 제품 ');
insert into mh_menu values(22,'핫크리스피버거',4700,'/burger_hotcri.jpg',2,'토마토와 레타스등의 야채와 하바네로香이 가미된 가슴살로 만든 매콤한 Premium 치킨버거');
insert into mh_menu values(23,'한우불고기',6700,'/burger_hanubul.jpg',2,'100% 우리 한우로 만든 두툼한 패티와 부드럽고 촉촉한 포테이토번이 만나 더 맛있어진 NEW 한우불고기 ');
insert into mh_menu values(24,'불고기버거',3500,'/burger_bulgogi.jpg',2,'볼륨 가득한 패티와 불고기 소스가 잘 조화된 영양만점의 햄버거');
insert into mh_menu values(25,'새우버거',3600,'/burger_sewu.jpg',2,'흰살생선과 새우맛이 살아있는 햄버거 세트 ');
insert into mh_menu values(26,'T-Rex버거',3500,'/burger_trex.jpg',2,'번스보다 큰 통다리살 치킨패티를 활용한 버거제품');
insert into mh_menu values(27,'비프바베큐버거',2000,'/burger_beef_bbq.jpg',2,'바베큐소스와 미트패티가 조화로운 실속 버거');
insert into mh_menu values(28,'클래식치즈버거',4000,'/burger_classic_cheese.jpg',2,'부드럽고 촉촉한 포테이토번과 풍부한 육즙의 두툼한 호주산 쇠고기패티로 본연의 맛을 꽉 채운 클래식 치즈버거 ');
insert into mh_menu values(29,'데리버거',2000,'/burger_deri.jpg',2,'풍성한 레터스에 마요네즈,독특한 데리소스가 포인트인 햄버거');
insert into mh_menu values(30,'아이스초코',2500,'/side_ice_choco.jpg',3,'달콤한 초코를 시원하게 즐길 수 있는 음료');
insert into mh_menu values(31,'콜라',1700,'/side_cola.jpg',3,'햄버거에 필수 음료 콜라');
insert into mh_menu values(32,'사이다',1700,'/side_cider.jpg',3,'톡톡 쏘는 청량감이 느껴지는 음료');
insert into mh_menu values(33,'우유',1000,'/side_milk.jpg',3,'신선한 롯데산록 우유');
insert into mh_menu values(34,'양념감자',2000,'/side_pot_season.jpg',3,'고객의 기호에 맞게 시즈닝(오니언,치즈,칠리)을 한가지를 선택해서 직접 뿌려먹는 새로운 방식의 포테이토 ');
insert into mh_menu values(35,'치즈스틱',2000,'/side_cheese_stick.jpg',3,'치즈에 파슬리를 첨가한 튀김옷을 입혀 바삭바삭하고 부드럽고 고소한 서구풍의 디저트 메뉴');
insert into mh_menu values(36,'베이컨 롱치즈스틱(1조각)',1900,'/side_bacon_long_cheese_stick.jpg',3,'베이컨 롱치즈스틱');
insert into mh_menu values(37,'치킨너겟',1000,'/side_chicken_nugget.jpg',3,'쵸코쿠키와 새콤달콤한 딸기 리플잼이 만나 새롭게 탄생한 토네이도 돼지');
insert into mh_menu values(38,'토네이도 돼지바',2300,'/side_tornado_with_strawberry_choco.jpg',3,'쵸코쿠키와 새콤달콤한 딸기 리플잼이 만나 새롭게 탄생한 토네이도 돼지');
insert into mh_menu values(39,'롱 치즈스틱',1700,'/side_long_cheese_stick.jpg',3,'치즈스틱이 길어졌다! 길이는 2배 길어지고 가격은 더 착해진 한정제품 롱 치즈스틱');
insert into mh_menu values(40,'해쉬브라운',1000,'/side_hashed_brown.jpg',3,'겉은 바삭하고 속은 촉촉하게 즐기는 감자 튀김 제품 ');
insert into mh_menu values(41,'콘샐러드',1500,'/side_corn_salad.jpg',3,'신선한 야채와 상큼하고 고소한 드레싱유가 잘 어우러진 맛의 제품');
insert into mh_menu values(42,'선데이아이스크림(스트로베리)',1500,'/side_sunday_icecream_strawberry.jpg',3,'부드러운 아이스크림에 진한 천연과일 소스를 얹어 향긋한 과일의 맛과 향을 더불어 즐길수있는 과일 아이스크림으로 상큼한 피치맛과 달콤한 스트로베리맛 두 종류가 있다.');
insert into mh_menu values(43,'쉑쉑치킨(칠리)',2500,'/side_shack_chicken_chili.jpg',3,'담백한 치킨 가슴살과 시즈닝이 조화로운 제품 ');
insert into mh_menu values(44,'쉑쉑치킨(치즈)',2500,'/side_shack_chicken_cheese.jpg',3,'담백한 치킨 가슴살과 시즈닝이 조화로운 제품 ');
insert into mh_menu values(45,'쉑쉑치킨(어니언)',2500,'/side_shack_chicken_onion.jpg',3,'담백한 치킨 가슴살과 시즈닝이 조화로운 제품 ');
insert into mh_menu values(46,'오징어링',2000,'/side_calamari_ring.jpg',3,'탱글탱글한 오징어살이 가득 씹히는 새로운 타입의 디저트 메뉴 ');
insert into mh_menu values(47,'포테이토',1500,'/side_potato.jpg',3,'신선도 높은 후라잉 오일에 바로 튀겨낸 바삭바삭하고 감칠맛 나는 맛의 후렌치 포테이토');
insert into mh_menu values(48,'초코쿠키 토네이도',2200,'/side_tornado_with_choco.jpg',3,'부드러운 아이스크림에 달콤하고 깔끔한 초코쿠키를 넣어 어린 아이부터 주부에 이르기까지 보는 즐거움과 먹는 즐거움을 함께하는 아이스크림 <일부매장제외>');
insert into mh_menu values(49,'녹차 토네이도',2200,'/side_tornado_with_greentea.jpg',3,'부드러운 아이스크림에 신선한 녹차를 넣어 풍부한 녹차향을 즐길수 있으며, 특히 10 ~ 30대 여성 취향의 제품으로 보는 즐거움과 먹는 즐거움을 함께하는 아이스크림 <일부매장제외>');
insert into mh_menu values(50,'스트로베리 토네이도',2300,'/side_tornado_with_strawberry.jpg',3,'딸기의 새콤달콤한 맛과 스트로베리 후레이크의 아삭 아삭한 맛이 좋아 천연 과일을 선호하는 고객을 위한 제품으로 보는 즐거움과 먹는 즐거움을 함께하는 아이스크림 <일부매장제외>');
insert into mh_menu values(51,'소프트콘',700,'/side_soft_cone.jpg',3,'부드러운 맛과 시원한 소프트 타입의 아이스콘 제품');
insert into mh_menu values(52,'마블소프트콘',800,'/side_marble_softcon.jpg',3,'소프트 아이스크림과 초코렛의 어우러진 디저트 메뉴');
insert into mh_menu values(53,'블루소다',2000,'/side_blue_soda.jpg',3,'톡 쏘는 탄산에 시럽을 넣어 마시는 제품');
insert into mh_menu values(54,'아이스 아메리카노L',2500,'/side_ice_americanol.jpg',3,'대용량 (20oz)으로 즐기는 시원한 아이스 아메리카노');
insert into mh_menu values(55,'사이다(S)',1000,'/side_ciders.jpg',3,'톡톡 쏘는 청량감이 느껴지는 음료');
insert into mh_menu values(56,'핫아메리카노(S)',1500,'/side_hot_americanos.jpg',3,'에스프레소 커피를 물로 희석하여 커피의 풍부한 맛을 살린 제품');
insert into mh_menu values(57,'스파클링 아이스티(S)',1000,'/side_sparkling_iced_teas.jpg',3,'탄산이 가미된 아이스티 음료');
insert into mh_menu values(58,'오렌지주스(400mlPET)',2500,'/side_orange_juice.jpg',3,'천연의 신선한 100% 오렌지 과즙이 함유된 후레쉬 드링크');
insert into mh_menu values(59,'망고피치',2500,'/side_mango_peach.jpg',3,'망고, 복숭아의 달콤한 맛과 감귤의 상큼한 맛이 조화로운 드링크 제품');
insert into mh_menu values(60,'스파클링 아이스티',1700,'/side_sparkling_iced_tea.jpg',3,'탄산이 가미된 아이스티 음료');
insert into mh_menu values(61,'콜라S',1000,'/side_cokes.jpg',3,'톡톡 쏘는 청량감이 느껴지는 음료');
insert into mh_menu values(62,'밀크쉐이크(딸기)',2100,'/side_milkshake_strawberry.jpg',3,'천연색소를 이용하여 만든 상큼한 딸기 쉐이크');
insert into mh_menu values(63,'밀크쉐이크(초코)',2100,'/side_milkshake_choco.jpg',3,'초코의 달콤함과 쉐이크의 부드러움이 잘 어울리는 제품');
insert into mh_menu values(64,'밀크쉐이크(바닐라)',2100,'/side_milkshake_vanilla.jpg',3,'달콤한 망고의 향과 맛이 느껴지는 시원한 쉐이크');
insert into mh_menu values(65,'아메리카노(H)',2000,'/side_americanoh.gif',3,'에스프레소 커피를 물로 희석하여 커피의 풍부한 맛을 살린 제품');
insert into mh_menu values(66,'아이스 아메리카노',2000,'/side_iced_americano.jpg',3,'차갑게 즐기는 맛이 풍부한 에스프레소 커피');
insert into mh_menu values(67,'카페라떼',2400,'/side_cafe_latte.gif',3,'에스프레소 커피에 따뜻한 우유를 듬뿍 넣어 부드럽게 즐기는 메뉴');
insert into mh_menu values(68,'아이스 카페라떼',2400,'/side_iced_cafe_latte.jpg',3,'에스프레소 커피와 시원한 우유가 잘 어우러진 제품');
insert into mh_menu values(69,'레몬에이드',2500,'/side_lemon_ade.jpg',3,'레몬의 상큼함을 상쾌하고 시원하게 즐길 수 있는 제품');